config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get 'home/about'
  get 'favorites/_favorite'
  root 'home#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :people
  resources :genres
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    collection do
      match 'search' => 'books#search', via: [:get, :post]
    end
  end
  resources :book_comments, only: [:create, :destroy, :edit, :update]

  post   '/favorites/:book_id' => 'favorites#create',   as: 'favorite'
  delete '/favorites/:book_id' => 'favorites#destroy', as: 'destroy'
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :book
	belongs_to :user
	validates :comment, presence:true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@book = Book.find(params[:book_id])
	    comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = @book.id
		if  comment.save
			flash[:notice] = "コメントが作成されました"
			@comment = BookComment.new
			@book_comment = @book.book_comments
		else
			@book = Book.find(params[:book_id])
			@comment = BookComment.new
			@book_comment = @book.book_comments
			  flash[:notice] = "コメントが作成できませんでした。"
		end
	end

	def edit
		@book_comment = BookComment.find(params[:id]).id
	end

	def update
		@book = Book.find(params[:book_id])
		@comment = BookComment.find(params[:id])
		if @comment.update(book_comment_params)
			flash[:notice] = "投稿が作成されました"
			redirect_to book_path(@comment.book)
		else
			@book = Book.find(params[:book_id])
			@comment = BookComment.find(params[:id])
			flash[:notice] = "コメントが作成できませんでした。"
		end
	end

	def destroy
		@book_comment = BookComment.find(params[:id])
		@book_comment.destroy
		redirect_to book_path(@book_comment.book)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment, :user_id)
	end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment.html.erb
<% book.book_comments.each do |book_comment| %>
<div class="book_comment">
	<%= render partial: 'book_comments/comment_partial', locals: { book_comment: book_comment } %>
</div>
<% end %>	

app/views/book_comments/_comment_form.html.erb
<%= form_for comment, remote: true do |f| %>
	<%= f.text_area :comment, rows: '5', class: "form-control", placeholder: "コメントをここに" %>
	<%= hidden_field_tag :book_id, book.id %>
	<%= f.submit "コメントを投稿する", :class => "btn btn-primary show" %>
<% end %>

app/views/book_comments/_comment_partial.html.erb
<div class="box1 clearfix" data-comment="<%= book_comment.id %>">
		<div class="comment">
			<%= book_comment.comment %>
		</div>

		<div class="show-left-contents">
			<div class="comment-date">
				<%= book_comment.created_at.strftime('%Y/%m/%d') %>
			</div>
			<%= link_to "削除", book_comment_path(book_comment), method: :delete, "data-confirm" => "本当に削除しますか？", :class => "btn btn-danger show" %>
			<%= link_to "編集", edit_book_comment_path(book_comment), remote: true, :class => "btn btn-primary show" %>
		</div>
		<div class="show-right-contents">
			<div class="comment-info">
				<%= attachment_image_tag book_comment.user, :profile_image, :fill, 60,60, :class => 'img-circle', fallback: "no_image.jpg" %>
			</div>
			<div class="comment-user">
				<%= book_comment.user.name %>
			</div>
		</div>
</div>

app/views/book_comments/_edit.html.erb
<div class="book_comment_partial row" data-comment="<%= @book_comment %>">
	<%= form_with(model: @book_comment, remote: true) do |f| %>
		<%= f.text_area :comment, rows: '5', class: "form-control", placeholder: "コメントをここに" %>
		<%= f.submit "コメントを投稿する", :class => "btn btn-primary show" %>
	<% end %>
</div>

app/views/book_comments/create.js.erb
$('#comment_area').html("<%= escape_javascript(render 'book_comment', book: @book) %>");
$('#comment_form').html("<%= escape_javascript(render 'comment_form', comment: @comment, book: @book) %>");

app/views/book_comments/edit.html.erb
<h1>回答編集ページ</h1>
<%= form_for [@comment] do |f| %>
	<%= f.text_area :comment, rows: '5', class: "form-control", placeholder: "コメントをここに" %>
	<%= f.submit "コメントを投稿する", :class => "btn btn-primary show" %>
<% end %>

<%= link_to "前に戻る", book_path(@comment.book) %>

app/views/book_comments/edit.js.erb
$('.row[data-comment="'+ @book_comment +'"]').parent().html("<%= escape_javascript(render 'edit') %>");

app/views/book_comments/edit_comment.js.erb
    <%= form_for @comment, remote: true do |f| %>
    <%= f.text_area :comment, rows: '5', class: "form-control", placeholder: "コメントをここに" %>
    <%= hidden_field_tag :book_id, book.id %>
    <%= f.submit "コメントを投稿する", :class => "btn btn-primary show" %>
    <% end %>