config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get 'home/about'
  get 'favorites/_favorite'
  root 'home#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :people
  resources :genres
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    collection do
      match 'search' => 'books#search', via: [:get, :post]
    end
  end
  resources :book_comments, only: [:create, :destroy, :edit, :update]

  post   '/favorites/:book_id' => 'favorites#create',   as: 'favorite'
  delete '/favorites/:book_id' => 'favorites#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	belongs_to :person
	belongs_to :genre
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	validates :body, presence:true

	def self.favorite
		 Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(3).pluck(:book_id))
	end

	def self.person
		Book.find(Book.group(:person_id).order('count(person_id) desc').limit(3).pluck(:person_id))
	end
	   
	def self.genre
		Book.find(Book.group(:genre_id).order('count(genre_id) desc').limit(3).pluck(:genre_id))
   	end

	def self.recent
		Book.order(created_at: "desc").limit(3)
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :book
	belongs_to :user
	validates :comment, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :book, counter_cache: :favorites_count
    belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :books, dependent: :destroy
	validates :genre_name, presence:true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :books, dependent: :destroy
	validates :person_name, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :back_image

  has_many :books,dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  validates :introduction, length: { maximum: 80 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!, only:[:show, :new, :create, :edit, :update, :destroy]
  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  		flash[:notice] = "投稿が作成されました"
  		redirect_to books_path
  	else
  		render "new"
  	end
  end

  def index
	if params[:books_name] == nil
		@books = Book.page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	elsif params[:books_name] == "2"
		@books = Book.order(favorites_count: "DESC").page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	elsif params[:books_name] == "1"
		@books = Book.order(created_at: "DESC").page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	end
  end

  def search
	if params[:person][:person_id].empty? && params[:genre][:genre_id].empty?
		@books = Book.page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
    elsif params[:person][:person_id].present? && params[:genre][:genre_id].empty?
		@person_id = params[:person][:person_id].to_i
		@books = Book.where(person_id: @person_id).page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	elsif params[:person][:person_id].empty? && params[:genre][:genre_id].present?
		@genre_id = params[:genre][:genre_id].to_i
		@books = Book.where(genre_id: @genre_id).page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	elsif params[:person][:person_id].present? && params[:genre][:genre_id].present?
		@person_id = params[:person][:person_id].to_i
		@genre_id = params[:genre][:genre_id].to_i
		@books = Book.where(person_id: @person_id, genre_id: @genre_id).page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	end
  end


  def show
  	@book = Book.find(params[:id])
  	@comment = BookComment.new
	@book_comment = Book.where(params[:book_id])
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	@book.user_id = current_user.id
  	if @book.update
  		flash[:notice] = "質問がが作成されました！"
  		redirect_to book_path(@book)
  	else
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path(@book)
  end

  private
  def book_params
  	params.require(:book).permit(:body, :person_id, :genre_id)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
	before_action :authenticate_user!
  def index
  	@genres = Genre.all
  end

  def new
  	@genre = Genre.new
  end

  def create
  	@genre = Genre.new(genre_params)
  	if @genre.save
  		flash[:notice] = "投稿が作成されました"
  		redirect_to genres_path
  	else
  		render "index"
  	end
  end

  def edit
  	@genre = Genre.find(params[:id])
  end

  def update
  	@genre = Genre.find(params[:id])
  	if @genre.update(genre_params)
  		flash[:notice] = "投稿が作成されました"
  		redirect_to genres_path
  	else
  		render "edit"
  	end
  end

  def destroy
  	@genre = Genre.find(params[:id])
  	@genre.destroy
  	redirect_to genres_path
  end

  private
  def genre_params
  	params.require(:genre).permit(:genre_name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @home_favorites = Book.favorite
    @person = Book.person
    @genre = Book.genre
    @recent = Book.recent
  end

  def about
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	before_action :authenticate_user!
  def new
  	@people = Person.new
  end

  def create
  	@people = Person.new(people_params)
  	if @people.save
  	   flash[:notice] = "登録が完了しました"
  	   redirect_to people_path
  	 else
  	 	render "new"
  	 end
  end

  def index
  	@people = Person.all
  end

  def edit
  	@people = Person.find(params[:id])
  end

  def update
  	@people = Person.find(params[:id])
  	if  @people.update(people_params)
  		flash[:notice] = "登録が完了しました"
  		redirect_to people_path
  	else
  		render "edit"
  	end
  end

  def destroy
  	@people = Person.find(params[:id])
  	@people.destroy
  	redirect_to people_path
  end

  private
  def people_params
  	params.require(:person).permit(:person_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only:[:edit, :update]
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:notice] = "登録が完了しました"
  		redirect_to user_path(@user)
  	else
  		render "edit"
  	end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to users_path
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :career, :wants, :skill, :license, :hobby, :back_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper 2.rb
module FavoritesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper 2.rb
module HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html 2.erb
<%= render 'favorites/favorite', book: book %>

app/views/books/_books.html.erb
<%= render 'favorites/favorite', book: book %>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div id="books">
<h1>みんなの質問</h1>
	<div class="q-index clearfix">
		<div class="q-index-right">
			<%= form_tag search_books_path, method: :get do %>
			<%= collection_select( :person, :person_id, Person.all, :id, :person_name, { :prompt => "人を選択" } ) %>
			<%= collection_select( :genre, :genre_id, Genre.all, :id, :genre_name, { :prompt => "ジャンルを選択" } ) %>
			<%= submit_tag "絞り込み" %>
			<% end %>
		</div>

		<div class="q-index-left">
			<%= form_tag books_path, method: :get do %>
				<%= select_tag "books_name", options_for_select([["新着順", "1"],["お気に入り順", "2"]]), {:prompt => "選択してください"} %>
				<%= submit_tag "切り替え" %>
			<% end %>
		</div>
	</div>


	<% @books.each do |book| %>
		<div class="box clearfix">
    	<%= link_to book_path(book) do  %>
			<div class="contents">
				<%= book.body %>
			</div>

            <div class="left-contents">
                <div class="person-name">
                    回答者：<%= book.person.person_name %>
                </div>
                <div class="genre-name">
                    ジャンル：<%= book.genre.genre_name %>
                </div>
                <div class="created_at">
                    作成日：<%= book.created_at.strftime('%Y/%m/%d') %>
                </div>
            </div>

            <% if user_signed_in? %>
				<div class="right-contents">
					<div class="books-favorite-link">
						<%= render partial: 'books/books', locals: {book: book} %>
					</div>
				</div>
			<% end %>
    <% end %>
	</div>
	<% end %>
	<%= paginate @books, class: "paginate" %>
</div>

app/views/books/new.html.erb
<div id="books">
	  <% if @book.errors.any? %>
	      <div id="error_explanation">
	        <h2><%= @book.errors.count %> つのエラーがあります</h2>
	        <ul>
	        <% @book.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	       <% end %>
	        </ul>
	      </div>
	  <% end %>

	<h1>新規投稿画面</h1>
	<%= form_for(@book) do |f| %>
		<h4>質問内容</h4>
		<%= f.text_area :body, rows: '5', class: "form-control" ,placeholder: "ここに質問を記入してください" %>
		<h4>誰に答えてほしいか</h4>
		<%= f.collection_select(:person_id, Person.all, :id, :person_name, { :prompt => "選択してください" , :multiple => true } ) %>
		<h4>ジャンル</h4>
		<%= f.collection_select(:genre_id, Genre.all, :id, :genre_name, { :prompt => "選択してください" , :multiple => true } ) %><br>
		<%= f.submit "質問を送る", :class => "btn btn-primary" %>
	<% end %>
</div>

app/views/books/show.html.erb
<div id="books">
<h1>質問内容</h1>
	<div class="box clearfix">
		<div class="contents">
			<%= @book.body %>
		</div>

		<div class="left-contents">
			<div class="person-name">
				回答者：<%= @book.person.person_name %>
			</div>
			<div class="genre-name">
				ジャンル：<%= @book.genre.genre_name %>
			</div>
			<div class="created_at">
				作成日：<%= @book.created_at.strftime('%Y/%m/%d') %>
			</div>
		</div>

		<% if user_signed_in? %>
			<div class="right-contents">
				<div class="books-favorite-link">
					<%= render partial: 'books/books', locals: {book: @book} %>
				</div>
			</div>
		<% end %>
	</div>

	<h2>↓↓質問に対する回答はこちら↓↓</h2>
		<div id="comment_area">
			<%= render partial: 'book_comments/book_comment', locals: { book: @book } %>
		</div>
	<br>
	<div id="comment_form">
		<%= render 'book_comments/comment_form', comment: @comment, book: @book %>
	</div>
</div>

app/views/genres/edit.html.erb
<% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= @genre.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1>ジャンル編集画面</h1>

<%= form_for(@genre) do |f| %>

<h4>名前</h4>
<%= f.text_field :genre_name %>

<%= f.submit "編集" %>

<% end %>

app/views/genres/index.html.erb
<h1>名前一覧画面</h1>

<table class="table table-striped">
	<tr>
		<th>ID</th>
		<th>名前</th>
		<th></th>
		<th></th>
	</tr>
	<% @genres.each do |genre| %>
	<tr>
		<th><%= genre.id %></th>
		<th><%= genre.genre_name %></th>
		<th><%= link_to "編集" , edit_genre_path(genre) %></th>
		<th><%= link_to "削除" , genre_path(genre), method: :delete %></th>
	</tr>
<% end %>
</table>

<%= link_to "新規登録", new_genre_path %>

app/views/genres/new.html.erb
<% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= @genre.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1>ジャンル投稿画面</h1>

<%= form_for(@genre) do |f| %>

<h4>名前</h4>
<%= f.text_field :genre_name %>

<%= f.submit "作成" %>

<% end %>

app/views/home/about.html 2.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/top.html.erb
<h2>最近の質問5選</h2>
<% @recent.each do |book| %>
    <div class="box clearfix">
    <%= link_to book_path(book) do  %>
			<div class="contents">
				<%= book.body %>
			</div>

            <div class="left-contents">
                <div class="person-name">
                    回答者：<%= book.person.person_name %>
                </div>
                <div class="genre-name">
                    ジャンル：<%= book.genre.genre_name %>
                </div>
                <div class="created_at">
                    作成日：<%= book.created_at.strftime('%Y/%m/%d') %>
                </div>
            </div>

            <% if user_signed_in? %>
                <div class="right-contents">
                    <div class="books-favorite-link">
                        <%= render partial: 'books/books', locals: {book: @book} %>
                    </div>
                </div>
            <% end %>
    <% end %>
	</div>
<% end %>

<h2>回答数が多い人</h2>
<% @person.each.with_index(1) do |book, i| %>
    <div class="box clearfix">
    <%= link_to book_path(book) do  %>
        <span class="">第<%= i %>位</span>
        <div class="contents">
            <%= book.body %>
        </div>

        <div class="left-contents">
            <div class="person-name">
                回答者：<%= book.person.person_name %>
            </div>
            <div class="genre-name">
                ジャンル：<%= book.genre.genre_name %>
            </div>
            <div class="created_at">
                作成日：<%= book.created_at.strftime('%Y/%m/%d') %>
            </div>
        </div>

        <% if user_signed_in? %>
            <div class="right-contents">
                <div class="books-favorite-link">
                    <%= render partial: 'books/books', locals: {book: @book} %>
                </div>
            </div>
        <% end %>
    <% end %>
	</div>
<% end %>

<h2>ジャンル多い順</h2>
<% @genre.each.with_index(1) do |book, i| %>
    <div class="box clearfix">
    <%= link_to book_path(book) do  %>
        <div class="">第<%= i %>位</div>
        <div class="contents">
            <%= book.body %>
        </div>

        <div class="left-contents">
            <div class="person-name">
                回答者：<%= book.person.person_name %>
            </div>
            <div class="genre-name">
                ジャンル：<%= book.genre.genre_name %>
            </div>
            <div class="created_at">
                作成日：<%= book.created_at.strftime('%Y/%m/%d') %>
            </div>
        </div>

        <% if user_signed_in? %>
            <div class="right-contents">
                <div class="books-favorite-link">
                    <%= render partial: 'books/books', locals: {book: @book} %>
                </div>
            </div>
        <% end %>
    <% end %>
	</div>
<% end %>

<h2>いいねが多い記事5選</h2>
<% @home_favorites.each.with_index(1) do |book, i| %>
    <div class="box clearfix">
    <%= link_to book_path(book) do  %>
        <div class="">第<%= i %>位</div>
        <div class="contents">
            <%= book.body %>
        </div>

        <div class="left-contents">
            <div class="person-name">
                回答者：<%= book.person.person_name %>
            </div>
            <div class="genre-name">
                ジャンル：<%= book.genre.genre_name %>
            </div>
            <div class="created_at">
                作成日：<%= book.created_at.strftime('%Y/%m/%d') %>
            </div>
        </div>

        <% if user_signed_in? %>
            <div class="right-contents">
                <div class="books-favorite-link">
                    <%= render partial: 'books/books', locals: {book: @book} %>
                </div>
            </div>
        <% end %>
    <% end %>
	</div>
<% end %>

app/views/people/edit.html.erb
<% if @people.errors.any? %>
    <div id="error_explanation">
      <h2><%= @people.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @people.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1>名前編集画面</h1>

<%= form_for(@people) do |f| %>

<h4>名前</h4>
<%= f.text_field :person_name %>

<%= f.submit "編集" %>

<% end %>

app/views/people/index.html.erb
<h1>名前一覧画面</h1>

<table class="table table-striped">
	<tr>
		<th>ID</th>
		<th>名前</th>
		<th></th>
		<th></th>
	</tr>
	<% @people.each do |person| %>
	<tr>
		<th><%= person.id %></th>
		<th><%= person.person_name %></th>
		<th><%= link_to "編集" , edit_person_path(person) %></th>
		<th><%= link_to "削除" , person_path(person), method: :delete %></th>
	</tr>
<% end %>
</table>

<%= link_to "新規登録", new_person_path %>

app/views/people/new.html.erb
<% if @people.errors.any? %>
    <div id="error_explanation">
      <h2><%= @people.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @people.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1>名前登録画面</h1>

<%= form_for(@people) do |f| %>

<h4>名前</h4>
<%= f.text_field :person_name %>

<%= f.submit "登録" %>

<% end %>

app/views/users/edit.html.erb
<div id="users">
<% if @user.errors.any? %>
	      <div id="error_explanation">
	        <h2><%= @user.errors.count %> error prohibited this user from being saved: </h2>
	        <ul>
	        <% @user.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	       <% end %>
	        </ul>
	      </div>
	  <% end %>
<%= form_for(@user) do |f| %>
	<h4>背景画像</h4>
	<%= f.attachment_field :back_image %>
	<h4>名前</h4>
	<%= f.text_field :name %>
	<h4>自己紹介文</h4>
	<%= f.text_area :introduction %>
	<h4>経歴</h4>
	<%= f.text_field :career %>
	<h4>これからしていきたいこと</h4>
	<%= f.text_area :wants %>
	<h4>スキル</h4>
	<%= f.text_field :skill %>
	<h4>資格</h4>
	<%= f.text_field :license %>
	<h4>趣味</h4>
	<%= f.text_area :hobby %>

	<%= f.submit "この内容を保存する" %>
<% end %>
</div>

app/views/users/index.html.erb
<h1>ユーザー一覧画面</h1>

	<% @users.each do |user| %>
		<%= link_to user_path(user) do %>
			<div id="users">
				<div class="profile-image"><%= attachment_image_tag user, :profile_image, :fill, 60,60,:class => 'img-circle', fallback: "no_image.jpg" %></div>
				<div class="user-name">
					<%= user.name %><br>
					<%= user.introduction %>
				</div>
			</div>
		<% end %>
	<% end %>

app/views/users/show.html.erb
<div id="users-show">
<h1>User詳細画面</h1>
	<%= link_to "編集", edit_user_path(@user), :class => "btn btn-primary" %>
	<h4>背景画像</h4>
	<%= attachment_image_tag @user, :back_image, :fill, 60,100 %>
	<h4>画像</h4>
	<%= attachment_image_tag @user, :profile_image, :fill, 60,60,:class => 'img-circle', fallback: "no_image.jpg" %>
	<h4>名前</h4>
	<%= @user.name %>
	<h4>自己紹介文</h4>
	<%= @user.introduction %>
	<h4>経歴</h4>
	<%= @user.career %>
	<h4>これからしていきたいこと</h4>
	<%= @user.wants %>
	<h4>スキル</h4>
	<%= @user.skill %>
	<h4>資格</h4>
	<%= @user.license %>
	<h4>趣味</h4>
	<%= @user.hobby %>
</div>