config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  get 'home/about'
  get 'favorites/_favorite'
  root 'home#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :people
  resources :genres
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    collection do
      match 'search' => 'books#search', via: [:get, :post]
    end
  end
  resources :book_comments, only: [:create, :destroy, :edit, :update]

  post   '/favorites/:book_id' => 'favorites#create',   as: 'favorite'
  delete '/favorites/:book_id' => 'favorites#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	belongs_to :person
	belongs_to :genre
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	validates :body, presence:true

	def self.favorite
		 Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(3).pluck(:book_id))
	end

	def self.person
		Book.find(Book.group(:person_id).order('count(person_id) desc').limit(3).pluck(:person_id))
	end
	   
	def self.genre
		Book.find(Book.group(:genre_id).order('count(genre_id) desc').limit(3).pluck(:genre_id))
   	end

	def self.recent
		Book.order(created_at: "desc").limit(3)
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :book
	belongs_to :user
	validates :comment, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :book, counter_cache: :favorites_count
    belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :books, dependent: :destroy
	validates :genre_name, presence:true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :books, dependent: :destroy
	validates :person_name, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :back_image

  has_many :books,dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  validates :introduction, length: { maximum: 80 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!, only:[:show, :new, :create, :edit, :update, :destroy]
  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  		flash[:notice] = "投稿が作成されました"
  		redirect_to books_path
  	else
  		render "new"
  	end
  end

  def index
	if params[:books_name] == nil
		@books = Book.page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	elsif params[:books_name] == "2"
		@books = Book.order(favorites_count: "DESC").page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	elsif params[:books_name] == "1"
		@books = Book.order(created_at: "DESC").page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	end
  end

  def search
	if params[:person][:person_id].empty? && params[:genre][:genre_id].empty?
		@books = Book.page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
    elsif params[:person][:person_id].present? && params[:genre][:genre_id].empty?
		@person_id = params[:person][:person_id].to_i
		@books = Book.where(person_id: @person_id).page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	elsif params[:person][:person_id].empty? && params[:genre][:genre_id].present?
		@genre_id = params[:genre][:genre_id].to_i
		@books = Book.where(genre_id: @genre_id).page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	elsif params[:person][:person_id].present? && params[:genre][:genre_id].present?
		@person_id = params[:person][:person_id].to_i
		@genre_id = params[:genre][:genre_id].to_i
		@books = Book.where(person_id: @person_id, genre_id: @genre_id).page(params[:page]).per(10)
		@favorite = Book.favorite
		render :index, locals: { books: @books, favorite: @favorite}
	end
  end


  def show
  	@book = Book.find(params[:id])
  	@comment = BookComment.new
	@book_comment = Book.where(params[:book_id])
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	@book.user_id = current_user.id
  	if @book.update
  		flash[:notice] = "質問がが作成されました！"
  		redirect_to book_path(@book)
  	else
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path(@book)
  end

  private
  def book_params
  	params.require(:book).permit(:body, :person_id, :genre_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @home_favorites = Book.favorite
    @person = Book.person
    @genre = Book.genre
    @recent = Book.recent
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only:[:edit, :update]
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:notice] = "登録が完了しました"
  		redirect_to user_path(@user)
  	else
  		render "edit"
  	end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to users_path
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :career, :wants, :skill, :license, :hobby, :back_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper 2.rb
module FavoritesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper 2.rb
module HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenQuestion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css" type="text/css" />
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" area-expanded="false" area-controls="navbar">
              <span class="sr-only">メニュー</span>
              <span class="icon-var"></span>
              <span class="icon-var"></span>
              <span class="icon-var"></span>
          </button>
          <nav class="nav navbar-nav navbar-left">
          <span class="title">OpenQuestion</span>
        </nav>
        </div>

        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "GS一覧", users_path %></li>
              <li><%= link_to "質問一覧", books_path %></li>
              <li><%= link_to "質問する", new_book_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "ホーム", "/" %></li>
              <li><%= link_to "ガイドライン", home_about_path %></li>
              <li><%= link_to "GS一覧", users_path %></li>
              <li><%= link_to "質問一覧", books_path %></li>
              <li><%= link_to "質問する", new_book_path %></li>
              <li><%= link_to "ログインする", new_user_session_path %></li>
              <li><%= link_to "新規登録する", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>


    <main>
      <div class="conteiner clearfix">
        <div class="row">
         <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
          <% if flash[:notice] %>
            <div class="flash">
              <%= flash[:notice] %>
            </div>
          <% end %>
          <%= yield %>
          </div>
        </div>
      </div>
    </main>

    <footer>
      <p class="copyright">©2019 WRL</p>
    </footer>
  </body>
</html>